// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MirrorDB;

namespace MirrorDB.Migrations
{
    [DbContext(typeof(MirrorDBContext))]
    [Migration("20200324024420_InitialMigrationCOVId")]
    partial class InitialMigrationCOVId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MirrorDB.FakeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName");

                    b.Property<string>("UserName2");

                    b.Property<string>("UserName3");

                    b.Property<bool>("active_bool")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("insert_by");

                    b.Property<DateTime>("insert_date")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2020, 3, 24, 9, 44, 20, 262, DateTimeKind.Local));

                    b.Property<string>("update_by");

                    b.Property<DateTime?>("update_date");

                    b.HasKey("Id");

                    b.ToTable("FakeTable","fake");
                });

            modelBuilder.Entity("MirrorDB.Models.dbMob.DTCovid2", b =>
                {
                    b.Property<bool>("active_bool")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("EmpNo");

                    b.Property<string>("HPNo");

                    b.Property<int>("Id");

                    b.Property<string>("Location");

                    b.Property<string>("Note");

                    b.Property<string>("Temp");

                    b.Property<DateTime>("TimeCheck");

                    b.Property<string>("insert_by");

                    b.Property<DateTime>("insert_date")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2020, 3, 24, 9, 44, 20, 262, DateTimeKind.Local));

                    b.Property<string>("update_by");

                    b.Property<DateTime?>("update_date");

                    b.HasKey("active_bool");

                    b.ToTable("DTCovid2","dbMob");
                });
#pragma warning restore 612, 618
        }
    }
}
